r"""Interactive manual tester for the `spreadsheet.*` functionality (Milestone 4).

This is a HUMAN-DRIVEN harness (not an automated test). It wires up the real
execution pipeline exactly as the agent will use it —

    ActionRegistry (+ SpreadsheetExecutor)
      → Dispatcher (+ AllowAllPolicy, VerificationRegistry (+ spreadsheet
        verifiers), InMemoryAuditSink)

— then lets you type spreadsheet commands and shows, for each one:
  * the resulting ActionStatus,
  * the bounded evidence the executor returned (sheets, dimensions, values),
  * the verification result (SKIPPED for reads; an INDEPENDENT re-read PASS/FAIL
    for `writecell`), and
  * the ordered audit trail emitted around the action.

Relative paths you type are resolved inside a throwaway `sandbox/` directory;
absolute paths are used as-is. Only `.xlsx` workbooks are supported.

To get started with no workbook of your own, run `sample` to generate a small
`sample.xlsx` (a 'Data' sheet with values + a 'Notes' sheet) inside the sandbox,
then exercise the commands against it.

RUN (from the windows-agent/ folder, using the project venv):

    & "..\.venv\Scripts\python.exe" tools\manual_spreadsheet_test.py
    # or point at a custom sandbox:
    & "..\.venv\Scripts\python.exe" tools\manual_spreadsheet_test.py --sandbox C:\tmp\wa

Type `help` at the prompt for the command list, `quit` to exit.

NOTE ON POLICY: this harness uses AllowAllPolicy, so every action is authorized
(the real deterministic policy arrives in M12). The point here is to exercise
SpreadsheetExecutor behaviour + the re-read write verifier, which is what M4
delivers.
"""

from __future__ import annotations

import argparse
import asyncio
import shlex
import sys
import uuid
from pathlib import Path

# Make the module importable when run as a plain script (sys.path[0] is tools/).
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from openpyxl import Workbook  # also used to synthesise the sample workbook  # noqa: E402

from windows_agent.audit import InMemoryAuditSink  # noqa: E402
from windows_agent.contracts import Action  # noqa: E402
from windows_agent.execution import ActionRegistry, Dispatcher  # noqa: E402
from windows_agent.executors import register_spreadsheet_executor  # noqa: E402
from windows_agent.policy import AllowAllPolicy  # noqa: E402
from windows_agent.verification import VerificationRegistry, register_spreadsheet_verifiers  # noqa: E402


HELP = """
Commands (paths are relative to the sandbox unless absolute; .xlsx only):
  sample [name]                    generate a sample workbook (default: sample.xlsx)
  ls                               list workbooks in the sandbox
  sheets <path>                    spreadsheet.list_sheets — sheet names
  dims <path> [sheet]              spreadsheet.dimensions   — used bounds
  readcell <path> <cell> [sheet]   spreadsheet.read_cell    — one cell's value
  readrange <path> <range> [sheet] spreadsheet.read_range   — a block of values
  writecell <path> <cell> <value...> [--sheet NAME]
                                   spreadsheet.write_cell   — set a cell (no overwrite)
  writecellover <path> <cell> <value...> [--sheet NAME]
                                   spreadsheet.write_cell   — set a cell, overwriting
  help                             show this help
  quit / exit                      leave

Try this quick scenario:
  sample
  sheets sample.xlsx
  dims sample.xlsx Data
  readcell sample.xlsx B2 Data
  readrange sample.xlsx A1:B3 Data
  writecell sample.xlsx C1 100 --sheet Data
  writecell sample.xlsx B2 999 --sheet Data      (fails: cell occupied)
  writecellover sample.xlsx B2 999 --sheet Data  (succeeds; reports previous)
"""

# Values baked into the generated sample workbook's 'Data' sheet.
_SAMPLE_ROWS = (
    ("Name", "Amount"),
    ("Widget", 42),
    ("Gadget", 7.5),
)


def _make_sample(path: Path) -> tuple[list[str], int]:
    """Create a small workbook with known sheets/values. Returns (sheets, bytes)."""
    wb = Workbook()
    data = wb.active
    data.title = "Data"
    for r, row in enumerate(_SAMPLE_ROWS, start=1):
        for c, value in enumerate(row, start=1):
            data.cell(row=r, column=c, value=value)
    notes = wb.create_sheet("Notes")
    notes["A1"] = "Generated by manual_spreadsheet_test"
    path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(str(path))
    sheets = list(wb.sheetnames)
    wb.close()
    return sheets, path.stat().st_size


def _coerce_value(token: str):
    """Best-effort scalar typing for a typed value: int, then float, else str."""
    try:
        return int(token)
    except ValueError:
        pass
    try:
        return float(token)
    except ValueError:
        return token


def _pop_sheet_flag(args: list[str]) -> tuple[list[str], str | None]:
    """Extract a trailing/inline `--sheet NAME` flag, returning (rest, sheet)."""
    if "--sheet" in args:
        i = args.index("--sheet")
        sheet = args[i + 1] if i + 1 < len(args) else None
        return args[:i] + args[i + 2 :], sheet
    return args, None


# Maps a typed command to (action_type, (target, params)).
def _build(cmd: str, args: list[str], resolve):
    if cmd == "sheets":
        return "spreadsheet.list_sheets", (str(resolve(args[0])), {})
    if cmd == "dims":
        params = {"sheet": args[1]} if len(args) > 1 else {}
        return "spreadsheet.dimensions", (str(resolve(args[0])), params)
    if cmd == "readcell":
        params = {"cell": args[1]}
        if len(args) > 2:
            params["sheet"] = args[2]
        return "spreadsheet.read_cell", (str(resolve(args[0])), params)
    if cmd == "readrange":
        params = {"range": args[1]}
        if len(args) > 2:
            params["sheet"] = args[2]
        return "spreadsheet.read_range", (str(resolve(args[0])), params)
    if cmd in ("writecell", "writecellover"):
        rest, sheet = _pop_sheet_flag(args[1:])
        if len(rest) < 2:
            raise ValueError("writecell needs <path> <cell> <value...>")
        cell, value = rest[0], _coerce_value(" ".join(rest[1:]))
        params = {"cell": cell, "value": value, "overwrite": cmd == "writecellover"}
        if sheet:
            params["sheet"] = sheet
        return "spreadsheet.write_cell", (str(resolve(args[0])), params)
    raise ValueError(f"Unknown command: {cmd!r} (type 'help')")


def _print_result(result, sink: InMemoryAuditSink) -> None:
    print(f"\n  status      : {result.status.value}")
    if result.evidence:
        print(f"  evidence    : {result.evidence}")
    if result.verification is not None:
        v = result.verification
        print(f"  verification: {v.status.value} ({v.method})")
        if v.message:
            print(f"                {v.message}")
        if v.expected is not None or v.observed is not None:
            print(f"                expected={v.expected!r} observed={v.observed!r}")
    if result.error is not None:
        print(f"  error       : [{result.error.code}] {result.error.message}")
    print("  audit trail :")
    for event in sink.events:
        tag = f" ({event.outcome})" if event.outcome else ""
        print(f"      - {event.event_type.value}{tag}: {event.summary}")
    print()


async def _run(sandbox: Path) -> None:
    registry = ActionRegistry()
    register_spreadsheet_executor(registry)
    verification = VerificationRegistry()
    register_spreadsheet_verifiers(verification)
    audit = InMemoryAuditSink()
    dispatcher = Dispatcher(registry, AllowAllPolicy(), verification=verification, audit=audit)

    task_id = uuid.uuid4().hex[:8]
    seq = 0
    resolve = lambda p: (Path(p) if Path(p).is_absolute() else sandbox / p)

    print(f"Sandbox: {sandbox}")
    print("Manual spreadsheet.* tester. Type 'help' for commands, 'sample' to make a test workbook, 'quit' to exit.")

    while True:
        try:
            line = input("xlsx> ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            break
        if not line:
            continue
        if line in ("quit", "exit"):
            break
        if line == "help":
            print(HELP)
            continue

        try:
            parts = shlex.split(line)
        except ValueError as exc:  # e.g. unbalanced quotes
            print(f"  parse error: {exc}")
            continue
        cmd, args = parts[0], parts[1:]

        # Local (non-pipeline) conveniences.
        if cmd == "sample":
            name = args[0] if args else "sample.xlsx"
            target = resolve(name)
            sheets, size = _make_sample(target)
            print(f"  created {target} (sheets={sheets}, {size} bytes)")
            continue
        if cmd == "ls":
            books = sorted(p.name for p in sandbox.glob("*.xlsx"))
            print(f"  {sandbox}:")
            print("    " + ("  ".join(books) if books else "(no workbooks — run 'sample')"))
            continue

        try:
            action_type, (target, params) = _build(cmd, args, resolve)
        except (ValueError, IndexError) as exc:
            print(f"  {exc}")
            continue

        action = Action(
            action_id=uuid.uuid4().hex[:8],
            task_id=task_id,
            sequence=seq,
            type=action_type,
            target=target,
            parameters=params,
            reason=f"manual: {line}",
        )
        seq += 1

        audit.events.clear()  # show only this action's events
        result = await dispatcher.dispatch(action)
        _print_result(result, audit)


def main() -> None:
    parser = argparse.ArgumentParser(description="Interactive manual tester for spreadsheet.* actions")
    parser.add_argument(
        "--sandbox",
        default=str(Path.cwd() / "sandbox"),
        help="Directory to operate in (created if missing). Default: ./sandbox",
    )
    ns = parser.parse_args()
    sandbox = Path(ns.sandbox).resolve()
    sandbox.mkdir(parents=True, exist_ok=True)
    asyncio.run(_run(sandbox))


if __name__ == "__main__":
    main()
